version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQl_DB: "hex-test"
      MYSQL_DATABASE: "hex-test"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Admin123"

    volumes:
      - ./testdb/:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
  grpc:
    build: .
    environment:
      DS_NAME: "root:Admin123@tcp(db:3306)/hex-test"
      DB_DRIVER: mysql
    command: ["go", "test", "-v", "./..."]